### ISSUE TITLE
Readme could use a comparison with competing solutions

### ISSUE THREAD

**Issue by serkandurusoy** [studiointeract/tracker-component#1]
Meteor-react-tracker-land is pretty much full of competing options where non has actually emerged as a best practice.

Therefore, the best thing a developer could do is read a comparison of those methods and decide for themselves.

It would be great if you could provide a basic comparison between
- tracker-component
- tracker-react
- react-komposer
- react-meteor-data

and provide some insight as to where your package falls short or supercedes the contenders.

And of course, thanks for providing this awesome package :)

**Comment by timbrandin** [comment]
Thx for feedback, I'll try to do that.

**Comment by timbrandin** [comment]
I'm working on a Guide on how to get started with Meteor 1.3 and Tracker.Component, I hope that'll solve this. :8ball:

**Comment by timbrandin** [comment]
I have updated the Readme with a comparison.
