### ISSUE TITLE
Why 20s timeout for stopping subs and comps?

### ISSUE THREAD

**Issue by serkandurusoy** [studiointeract/tracker-component#2]
Within [`componentWillUnmount`](https://github.com/studiointeract/tracker-component/blob/master/lib/index.jsx#L50) you are specificaly waiting exactly 20 seconds before stopping existing subscriptions and computations. 

``` javscript
componentWillUnmount() {
  setTimeout(() => {
    Object.keys(this.__subs).forEach(sub => this.__subs[sub].stop());
    this.__comps.forEach(comp => comp.stop());
  }, 20000);
}
```

Why not immediately? Why exactly 20 seconds?

**Comment by timbrandin** [comment]
Good call, will have another look at this, the reason is that the DDP messages could for some reason end up in the wrong order.

**Comment by timbrandin** [comment]
I don't see this as a big problem, but will investigate when there's more time. Works like a charm as it is.

**Comment by timbrandin** [comment]
Closing for now, but will investigate.

**Comment by serkandurusoy** [comment]
Hmm I thought DDP guaranteed message order.

Do you have a replication of the issue that I could perhaps work on?

Also, you could perhaps try "reversing" the array of subs/comps and then iterating over them to stop, but each within their own Meteor.defer() and Tracker.afterFlush() respectively

**Comment by timbrandin** [comment]
I love that idea, I'll see if I can setup a repo for that.

**Comment by serkandurusoy** [comment]
Hmm, might this be related:

https://github.com/ultimatejs/tracker-react/blob/master/main.js#L40

**Comment by timbrandin** [comment]
I think I know the issue now, it seams like I'm subscribing multiple times on the same subscription, that causes Meteor to unsubscribe by some reason. I'm looking at implementing the full subscribe solution from https://github.com/meteor/meteor/blob/master/packages/blaze/template.js#L347

**Comment by timbrandin** [comment]
I don't think me unsubscribing was the issue at all.

**Comment by timbrandin** [comment]
I found the issue, it was related to rerunning subscriptions when the state changed by the same method, I've cleared this out now, and also it turns out we need less code with all these learnings, down to 50 lines once again.

**Comment by serkandurusoy** [comment]
Wow, great catch! I had not even considered taking a step back to see the broader picture.
