### ISSUE TITLE
A container example in the readme

### ISSUE THREAD

**Issue by serkandurusoy** [studiointeract/tracker-component#4]
In light of the suggestions by the guide and accepted pattern best practice, developers tend to remove data and presentation in the form of container components wrapped by stateless dummy components.

I know this too can be very easily achieved by using tracker-component using it to create a data wrapper to pass data as props to enclosed ui components.

But, since many people are new to react, the current contents of the readme may create the illusion that tracer-component is not fit to create container components.

Thus, to mitigate such false perception, readme could benefit from including a version of the examples that create a container that pass the data as props to another child component that represents the render function's html structure contained in its own stateless funtional component.

**Comment by serkandurusoy** [comment]
In fact, a note about the ability to use the pure renderer mixin for simpler data structures could also help understand that this is not just a toy component, but a simple but clever solution.

**Comment by timbrandin** [comment]
Could you explain "the pure renderer mixin for simpler data structures", I'm not sure I get it. I'm on it, adding a Composition example in the Readme, great idea!

**Comment by serkandurusoy** [comment]
As described on its own [documentation](https://facebook.github.io/react/docs/pure-render-mixin.html) this is a utility to increase rendering performance for react components where
- the render function is a pure function of its props
- the props are not nested data structures (more on this on the docs)

Here's the official ES6 example:

``` javascript
import PureRenderMixin from 'react-addons-pure-render-mixin';
class FooComponent extends React.Component {
  constructor(props) {
    super(props);
    this.shouldComponentUpdate = PureRenderMixin.shouldComponentUpdate.bind(this);
  }

  render() {
    return <div className={this.props.className}>foo</div>;
  }
}
```

This is not anyhing special, or something you need to pay special attention to, but is just worth a mention on the readme that tracker-component is compatible with this since tracker itself already does heavy lifting of diffing incoming data structures.

**Comment by timbrandin** [comment]
You mean with something like this:

``` javascript
class Composition extends React.Component {
  constructor(props) {
    super(props);
    this.subscribe('cars');
    this.autorun(() => {
      this.setState({
        cars: Models.find().fetch()
      });
    });
  }

  render() {
    let { children = [] } = this.props;
    return <div>{children.map(Child => <Child {...this.state} />)}</div>;
  }
}

const Cars = ({ cars = [] }) => (
  <ul className="cars">
    {cars.map(car =>
      <li className="car">{car.brand} {car.model}</li>
    )}
  </ul>
);

const MainLayout = ({content}) => (
  <main>{content}</main>
);

FlowRouter.route("/", {
  action() {
    ReactLayout.render(MainLayout, {
      content: <Composition><Cars /></Composition>
    });
  }
});
```

**Comment by serkandurusoy** [comment]
Cool!

**Comment by timbrandin** [comment]
I've added this example to the Readme and linked from the top, thx for contributing! :dancer:

**Comment by serkandurusoy** [comment]
The readme is becoming quite a document now! Kudos!

**Comment by PEM--** [comment]
@timbrandin : Kudos for the library. I've just started using it. So far, so good :+1: 

For the component model, I didn't get the first example. For me, React needs to create a shallow copy of the children transmitted to the component model (the real views) and inject the `cars` as props.

``` js
// main.jsx

import React from 'react';
import Tracker from 'tracker-component';

Models = new Mongo.Collection('models');
if (Meteor.isServer) {
  Meteor.publish('cars', () => Models.find());
}

class Models extends Tracker.Component {
  constructor(props) {
    super(props);
    this.subscribe('cars');
    this.autorun(() => {
      this.setState({
        cars: Models.find().fetch()
      });
    });
  }
  // *** PEM: Rendering with shallow copies and expending children props
  render() {
    const { children } = this.props;
    const { cars } = this.state;
    const childrenWithProps = React.Children.map(children, (child) =>
      React.cloneElement(child, { cars }));
    return childrenWithProps;
  }
  // *** PEM
}

const Cars = ({ cars = [] }) => (
  <ul className="cars">
    {cars.map(car =>
      <li className="car">{car.brand} {car.model}</li>
    )}
  </ul>
);

if (Meteor.isClient) {
  Meteor.startup(() => {
    ReactDOM.render(<Models><Cars /></Models>, document.body);
  });
}
```

Did I miss something?

**Comment by timbrandin** [comment]
Yeah, that's right, it's the same method used by createComponent (ReactMeteorData) behind the scenes.

Though Tracker.Component does all this for you already for all the children of the Model.
It passes down the state as props to all of the children in the Model component, unless if you override the render method and create your own implementation.

See this snippet for example:
https://github.com/studiointeract/tracker-component/blob/master/lib/index.jsx#L43-L44

**Comment by PEM--** [comment]
Yep, seen this. But it didn't work out for me. On the server side, children have no map.

Did you meet this issue when using server side with FlowRouter-ssr and react-mounter?
