### ISSUE TITLE
Test for nested components

### ISSUE THREAD

**Issue by serkandurusoy** [studiointeract/tracker-component#5]
According to the comments from ultimatejs:traker-react, `componentWillUnmount()` is only run within the topmost component and any inner components that o clean ups using it will be left stale.

To avoid that, tracker-react uses low level prototype methods, but official react recommendation is extending React.Component with your own component where you have a call to [super.componentWilUnmount()](https://github.com/facebook/react/issues/6162)

This gets me thinking, although I have not yet tried it, how does tracker-component behave when there are nested Tracker.Component's?

Lets say we have a Post component which fetches a post from a posts collection and within that we make a call (within a comments.map((id)=><Comment id=id/>)) to a comment component which itself subscribes and fetches a comment from a comments collection.

In such a case, does it behave well, do all cleanups get fired?

**Comment by timbrandin** [comment]
I've tested nested components with Tracker.Component actually, this is where I found the issue on the subscriptions actually. It works like a charm, though there might be an issue if the implementing methods re-implements componentWillUnmount method, I have to check.

**Comment by timbrandin** [comment]
I've added a some notes that you'll need to call super if you extend the componentWillUpdate or componentWillUnmount. That's what you need to do.

**Comment by serkandurusoy** [comment]
That's great to hear! I thought [this line itself](https://github.com/studiointeract/tracker-component/blob/master/lib/index.jsx#L44) would have needed a `super.componentWilUnmount()` call but if it does not, all the better!

**Comment by timbrandin** [comment]
You only need to call `super.componentWilUnmount()` to notify the super implementation, I don't think you need it to get the children to themself get that callback.

**Comment by serkandurusoy** [comment]
Hmm yes, I think I was looking at it backwards. Thinking of it, I think it may be a good practice to always call `super.componentWilUnmount()` from within our components to make sure they run, because what I understand from that bug report is that componentWilUnmount() is somehow not automatically inherited while other lifecycle methods are.

**Comment by timbrandin** [comment]
Yeah, I doesn't hurt I think, but we do need a case to test if this is an actual issue, so that we verify it is not something they noted with their complex setup I mean.

**Comment by serkandurusoy** [comment]
Well, hopefully I will have a fairly large test case in a few weeks becasue I'm kicking off this largish line of business app and I'm meaning to use this for my data integration. So you'll definitely be getting lots of input from me :)

**Comment by timbrandin** [comment]
Oh great! When we find if there might be an issue, we should create a test for it too

**Comment by serkandurusoy** [comment]
Hmm that may require setting up shallow render and enzyme.

**Comment by timbrandin** [comment]
Doesn't meteor have full app testing support now?

**Comment by serkandurusoy** [comment]
Yes but it does not provide an out of box way to actually render react components, which enzyme and shallow render provide

**Comment by timbrandin** [comment]
Alright, I have to read up on that.
