### ISSUE TITLE
How to handle parent state?

### ISSUE THREAD

**Issue by dnish** [studiointeract/tracker-component#9]
Hey,
I'm having an issue with autorun and setting the state of a parent. For example, I'm having cateogry items which also have subcat items:

Category A
- Sub 1
- Sub 2

Category B
- Sub 3
- Sub 4

Now, if I visit Sub 4, the state of Category B and Sub 4 should be go to active.

In my sub component, my code looks like this:

```
export class CategorySubItem extends Tracker.Component {

    constructor(props) {
        super(props);

        this.state = {
            active: false
        };

        this.autorun(() => {
            if(LayoutGlobals.get().categoryId == this.props.doc.id) {
                this.setState({active:true});
                this.props.parent.setState({active:true});
            } else {
                this.setState({active:false});
                this.props.parent.setState({active:false});
            }
        });




    }
```

When I set the state of my parent, I'm ending up in an infinite loops of rerenders. What would be the correct way to handle this?

**Comment by timbrandin** [comment]
@dnish did you solve this by yourself?

**Comment by dnish** [comment]
@timbrandin yes, my code above violates the "top down architecture" of React. The problem is that I've set the parent state within the constructor of the child component. This isn't allowed. Setting it f.e. in componentDidMount fixes that problem.
